development:
  adapter: postgresql
  encoding: unicode
  database: ab_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ab_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ab_production
  pool: 5
  timeout: 5000
